---

name: CI/CD

on:
  merge_group:
  push:
    branches:
    - master
    - >-
      [0-9].[0-9]+
    tags:
    - v*
  pull_request:
    branches:
    - master
    - >-
      [0-9].[0-9]+
  

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true


env:
  COLOR: >-  # Supposedly, pytest or coveragepy use this
    yes
  FORCE_COLOR: 1  # Request colored output from CLI tools supporting it
  MYPY_FORCE_COLOR: 1  # MyPy's color enforcement
  PIP_DISABLE_PIP_VERSION_CHECK: 1
  PIP_NO_PYTHON_VERSION_WARNING: 1
  PIP_NO_WARN_SCRIPT_LOCATION: 1
  PRE_COMMIT_COLOR: always
  PROJECT_NAME: frozenlist
  PY_COLORS: 1  # Recognized by the `py` package, dependency of `pytest`
  PYTHONIOENCODING: utf-8
  PYTHONUTF8: 1
  PYTHON_LATEST: 3.x


jobs:

  
  test:
    name: Test
    strategy:
      matrix:
        pyver:
        - 3.13
       
        no-extensions: ['', 'Y']
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
        experimental: [false]
        exclude:
        - os: macos-latest
          no-extensions: Y
        - os: windows-latest
          no-extensions: Y
        include:
        - pyver: pypy-3.10
          no-extensions: Y
          experimental: false
          os: ubuntu-latest
        - pyver: pypy-3.9
          no-extensions: Y
          experimental: false
          os: ubuntu-latest
      fail-fast: false
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    continue-on-error: ${{ matrix.experimental }}
    steps:
    - name: Retrieve the project source from an sdist inside the GHA artifact
      uses: re-actors/checkout-python-sdist@release/v2
      with:
        source-tarball-name: >-
          ${{ needs.build-pure-python-dists.outputs.sdist-filename }}
        workflow-artifact-name: >-
          ${{ needs.pre-setup.outputs.dists-artifact-name }}
    - name: Download distributions
      uses: actions/download-artifact@v4
      with:
        path: dist
        pattern: ${{ needs.pre-setup.outputs.dists-artifact-name }}*
        merge-multiple: true

    - name: Setup Python ${{ matrix.pyver }}
      id: python-install
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.pyver }}
        allow-prereleases: true
        cache: pip
        cache-dependency-path: requirements/*.txt
    
